### ISSUE TITLE
导入之后，某个类出现了问题！

### ISSUE THREAD

**Issue by zqq525** [xiaoyaoyou1212/BluetoothChat#1]
![baidushurufa_2017-1-13_23-25-2](https://cloud.githubusercontent.com/assets/9776629/21935224/b34cc392-d9e7-11e6-9de0-e0365ea626f2.png)
StorageUtils.getRootPath(Contect context)这个方法找不到。可能是导入的包有问题，但我不知道应该是什么包，所以希望您解答一下。谢谢

**Comment by xiaoyaoyou1212** [comment]
这个是FilePicker库提供的，估计是作者把这个方法改名字了，你在那个类中再找找对应的方法。

**Comment by MASAILA** [comment]
getInternalRootPath
