### ISSUE TITLE
项目无法使用

### ISSUE THREAD

**Issue by TommyFen** [xiaoyaoyou1212/BluetoothChat#2]
把项目clone下来安装到一个荣耀(4.4)和一个魅族（5.1），一直显示离线状态。一旦进入聊天界面，在荣耀中崩溃，在魅族上一直卡进度条

**Comment by tucaoxingren** [comment]
我用android studio 直接都编译不了

**Comment by xiaoyaoyou1212** [comment]
@tucaoxingren 具体要看报什么错误，对应解决呗

**Comment by xiaoyaoyou1212** [comment]
@Tommy-Fen 如果崩溃，具体需要看下日志
