### ISSUE TITLE
增加好友的时候没有自动配对

### ISSUE THREAD

**Issue by almighty1982** [xiaoyaoyou1212/BluetoothChat#3]
增加好友的时候，发现的问题：
1、设备列表不完整，例如：A手机搜索的时候使用蓝牙搜索，可以搜索到B手机，如果使用BluetoothChat软件中好友搜索，不能搜索到对应的B手机
2、添加好友的时候不是自动添加，选择添加好友，会弹出蓝牙配对的确认信息，需要A和B手机分别点确认才能配对成功（A和B都是使用BluetoothChat软件的，依然会弹出）

不是很清楚是否本身是这样设计，从说明看，应该是自动配对，查找的时候有120秒的时间查找，应该能查找完整才对
@xiaoyaoyou1212

**Comment by xiaoyaoyou1212** [comment]
@almighty1982 第一个问题，看下设备是否已经配对过，这个扫描是系统方法没什么特殊处理的；第二个问题，配对是需要对方进行确认的，实际上是一种验证手段，如果你想隐藏这一步也是可以的，但是需要做一些特殊处理。

**Comment by almighty1982** [comment]
多谢 @xiaoyaoyou1212 
第一个问题发现确实没有配对过，我正在分析
第二个android手机跟手机之间是否可以做到自动配对并且给用户不显示提示信息，这个是否有方案，咨询你一下

**Comment by xiaoyaoyou1212** [comment]
@almighty1982 手机与手机配对应该都会有这个弹窗

**Comment by almighty1982** [comment]
多谢 @xiaoyaoyou1212 

手机跟手机配对确实都会有这个弹窗，因为蓝牙的连接模式有下面几种：
Numeric Comparison：配对双方都显示一个6位的数字，由用户来核对数字是否一致，一致即可配对。例如手机之间的配对。
Just Works：用于配对没有显示没有输入的设备，主动发起连接即可配对，用户看不到配对过程。例如连接蓝牙耳机。
Passkey Entry：要求配对目标输入一个在本地设备上显示的6位数字，输入正确即可配对。例如连接蓝牙键盘。
Out of Band：两设备的通过别的途径交换配对信息，例如NFC等。例如一些NFC蓝牙音箱。
具体使用哪种模式，依赖于从端的模式配置，穿戴设备都是just work模式，因此，可以不需要提示，但是，手机为了安全，不会设置just work模式，因此，必须要配置

**Comment by almighty1982** [comment]
第一个问题也已经解决，没有发现的原因是现在打开app后，也不会打开蓝牙发现开关，只有进入蓝牙界面，才会打开蓝牙发现开关，因此，按照现在的处理也是正常的
这个地方是否可以优化，在打开BT chat程序的时候，默认打开蓝牙发现开关，这样，如果打开程序的手机之间就可以互相发现了

@xiaoyaoyou1212

**Comment by xiaoyaoyou1212** [comment]
@almighty1982 谢谢关于配对的解惑，我这个demo只是提供一种思路，如果想修改处理方式可以自行修改哟

**Comment by almighty1982** [comment]
多谢 @xiaoyaoyou1212 ，那我再看看这个demo代码，这个问题疑问已经解答，我将ISSUE闭环了
