### ISSUE TITLE
咨询：BluetoothChat 程序中使用的是经典蓝牙还是BLE

### ISSUE THREAD

**Issue by almighty1982** [xiaoyaoyou1212/BluetoothChat#4]
我安装程序后看到程序显示的是BLE，但是，从代码看，感觉应该是经典蓝牙，请问具体使用的是BLE还是经典蓝牙

@xiaoyaoyou1212

**Comment by xiaoyaoyou1212** [comment]
@almighty1982 这个是经典蓝牙的哦，如果想了解BLE相关的可以看另一个项目https://github.com/xiaoyaoyou1212/BLE

**Comment by almighty1982** [comment]
OK，多谢 @xiaoyaoyou1212
